### ISSUE TITLE
No Method Error: undefined method 'helpers' for nil when redirecting root

### ISSUE THREAD

**Issue by gobijan** [hotwired/spark#53]
First of all thanks for making this Gem. It's very nice to have this as default for new Rails apps rather sooner than later.

I just updated to the latest version an get this error when visiting my application root "/"
I used root to redirect to foo in my routes.rb:

    root to: redirect("/foos")

Other routes work but @request.controller_instance is nil when the spark middleware kicks in so it panics:

```
NoMethodError
undefined method 'helpers' for nil

[hotwire-spark (0.1.11) lib/hotwire/spark/middleware.rb:42:in 'Hotwire::Spark::Middleware#view_helpers'](http://127.0.0.1:3000/#)
[hotwire-spark (0.1.11) lib/hotwire/spark/middleware.rb:37:in 'Hotwire::Spark::Middleware#script_tag'](http://127.0.0.1:3000/#)
[hotwire-spark (0.1.11) lib/hotwire/spark/middleware.rb:33:in 'Hotwire::Spark::Middleware#inject_javascript'](http://127.0.0.1:3000/#)
[hotwire-spark (0.1.11) lib/hotwire/spark/middleware.rb:12:in 'Hotwire::Spark::Middleware#call'](http://127.0.0.1:3000/#)
[rack (3.1.8) lib/rack/tempfile_reaper.rb:20:in 'Rack::TempfileReaper#call'](http://127.0.0.1:3000/#)
[rack (3.1.8) lib/rack/etag.rb:29:in 'Rack::ETag#call'](http://127.0.0.1:3000/#)
[rack (3.1.8) lib/rack/conditional_get.rb:31:in 'Rack::ConditionalGet#call'](http://127.0.0.1:3000/#)
[rack (3.1.8) lib/rack/head.rb:15:in 'Rack::Head#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/http/permissions_policy.rb:38:in 'ActionDispatch::PermissionsPolicy::Middleware#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/http/content_security_policy.rb:38:in 'ActionDispatch::ContentSecurityPolicy::Middleware#call'](http://127.0.0.1:3000/#)
[rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in 'Rack::Session::Abstract::Persisted#context'](http://127.0.0.1:3000/#)
[rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in 'Rack::Session::Abstract::Persisted#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/cookies.rb:706:in 'ActionDispatch::Cookies#call'](http://127.0.0.1:3000/#)
[activerecord (8.0.1) lib/active_record/migration.rb:671:in 'ActiveRecord::Migration::CheckPending#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/callbacks.rb:31:in 'block in ActionDispatch::Callbacks#call'](http://127.0.0.1:3000/#)
[activesupport (8.0.1) lib/active_support/callbacks.rb:100:in 'ActiveSupport::Callbacks#run_callbacks'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/callbacks.rb:30:in 'ActionDispatch::Callbacks#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/executor.rb:16:in 'ActionDispatch::Executor#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in 'ActionDispatch::ActionableExceptions#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:31:in 'ActionDispatch::DebugExceptions#call'](http://127.0.0.1:3000/#)
[web-console (4.2.1) lib/web_console/middleware.rb:132:in 'WebConsole::Middleware#call_app'](http://127.0.0.1:3000/#)
[web-console (4.2.1) lib/web_console/middleware.rb:28:in 'block in WebConsole::Middleware#call'](http://127.0.0.1:3000/#)
[web-console (4.2.1) lib/web_console/middleware.rb:17:in 'Kernel#catch'](http://127.0.0.1:3000/#)
[web-console (4.2.1) lib/web_console/middleware.rb:17:in 'WebConsole::Middleware#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/show_exceptions.rb:32:in 'ActionDispatch::ShowExceptions#call'](http://127.0.0.1:3000/#)
[railties (8.0.1) lib/rails/rack/logger.rb:41:in 'Rails::Rack::Logger#call_app'](http://127.0.0.1:3000/#)
[railties (8.0.1) lib/rails/rack/logger.rb:29:in 'Rails::Rack::Logger#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/remote_ip.rb:96:in 'ActionDispatch::RemoteIp#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/request_id.rb:34:in 'ActionDispatch::RequestId#call'](http://127.0.0.1:3000/#)
[rack (3.1.8) lib/rack/method_override.rb:28:in 'Rack::MethodOverride#call'](http://127.0.0.1:3000/#)
[rack (3.1.8) lib/rack/runtime.rb:24:in 'Rack::Runtime#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/server_timing.rb:61:in 'block in ActionDispatch::ServerTiming#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/server_timing.rb:26:in 'ActionDispatch::ServerTiming::Subscriber#collect_events'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/server_timing.rb:60:in 'ActionDispatch::ServerTiming#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/executor.rb:16:in 'ActionDispatch::Executor#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/static.rb:27:in 'ActionDispatch::Static#call'](http://127.0.0.1:3000/#)
[rack (3.1.8) lib/rack/sendfile.rb:114:in 'Rack::Sendfile#call'](http://127.0.0.1:3000/#)
[actionpack (8.0.1) lib/action_dispatch/middleware/host_authorization.rb:143:in 'ActionDispatch::HostAuthorization#call'](http://127.0.0.1:3000/#)
[railties (8.0.1) lib/rails/engine.rb:535:in 'Rails::Engine#call'](http://127.0.0.1:3000/#)
[puma (6.5.0) lib/puma/configuration.rb:279:in 'Puma::Configuration::ConfigMiddleware#call'](http://127.0.0.1:3000/#)
[puma (6.5.0) lib/puma/request.rb:99:in 'block in Puma::Request#handle_request'](http://127.0.0.1:3000/#)
[puma (6.5.0) lib/puma/thread_pool.rb:389:in 'Puma::ThreadPool#with_force_shutdown'](http://127.0.0.1:3000/#)
[puma (6.5.0) lib/puma/request.rb:98:in 'Puma::Request#handle_request'](http://127.0.0.1:3000/#)
[puma (6.5.0) lib/puma/server.rb:468:in 'Puma::Server#process_client'](http://127.0.0.1:3000/#)
[puma (6.5.0) lib/puma/server.rb:249:in 'block in Puma::Server#run'](http://127.0.0.1:3000/#)
[puma (6.5.0) lib/puma/thread_pool.rb:166:in 'block in Puma::ThreadPool#spawn_thread'](http://127.0.0.1:3000/#)
```

**Comment by gobijan** [comment]
Just added a PR that does some nil checking so my app works again. Check it out and let me know if it makes sense to you.
